name: AI Terraform Bot

on:
  issue_comment:
    types: [created]

jobs:
  ai:
    # Only run if the comment contains /create-vm
    if: contains(github.event.comment.body, '/create-vm')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install openai>=1.0.0

      - name: Parse comment
        id: parse
        run: |
          echo "USER_INPUT=${GITHUB_EVENT_COMMENT_BODY}" >> $GITHUB_ENV
      
      - name: Generate Terraform code with AI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          USER_INPUT: ${{ env.USER_INPUT }}
        run: |
          python3 << 'EOF'
          import os
          from openai import OpenAI

          client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
          user_input = os.getenv("USER_INPUT")

          # Construct prompt from comment
          prompt = f"""
          The user requested: {user_input}
          Write Terraform code that adds a new Azure Ubuntu VM.
          Requirements:
          - Resource group: rg-ubuntu-vm
          - Use azurerm_linux_virtual_machine
          - Default Ubuntu version: 20.04 LTS if not specified
          - Default VM size: Standard_B1s if not specified
          """

          response = client.chat.completions.create(
              model="gpt-3.5-turbo",  # or your Azure OpenAI deployment name
              messages=[{"role": "user", "content": prompt}],
              temperature=0.2
          )

          code = response.choices[0].message.content

          with open("vm.tf", "w") as f:
              f.write(code)

          print("✅ Terraform code generated in vm.tf")
          EOF

      - name: Commit changes using GitHub Actions bot identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add vm.tf
          git commit -m "AI Bot: Add VM from issue comment" || echo "No changes to commit"
          git push
