name: Terraform Deploy to Azure

on:
  push:
    branches:
      - main
    paths:
      - '**/*.tf'
      - 'terraform.tfvars'

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure Azure Credentials
        run: echo "Azure credentials loaded"
        env:
          TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      - name: Terraform Init
        run: terraform init -backend-config "subscription_id=$TF_VAR_subscription_id" -backend-config "tenant_id=$TF_VAR_tenant_id" -backend-config "client_id=$TF_VAR_client_id" -backend-config "client_secret=$TF_VAR_client_secret"

      - name: Terraform Plan
        run: terraform plan 
        
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
