on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
    paths:
      - '**/*.tf'
      - 'terraform.tfvars'

jobs:
  terraform:
    name: 'Terraform'
    env: 
      TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
      TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false

    - name: Terraform init
      run: terraform init -backend-config "subscription_id=$TF_VAR_subscription_id" -backend-config "tenant_id=$TF_VAR_tenant_id" -backend-config "client_id=$TF_VAR_client_id" -backend-config "client_secret=$TF_VAR_client_secret"

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      if: github.event_name == 'push'
      run: terraform apply -auto-approve -input=false
      
    # Destroy the VM and the assisositate resources
    - name: Terraform destroy
      run: terraform destroy -auto-approve -input=false
